[package]
name = "tophat"
version = "0.1.0"
authors = ["Walther Chen <walther.chen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.1"
futures-core = "0.3.4"
futures-io = "0.3.4"
http-body = "0.3.1"
bytes = "0.5.4"
httparse = "1.3.4"
futures-util = "0.3.4"

[dev-dependencies]
smol = "0.1.4"
