[package]
name = "tophat"
version = "0.1.0"
authors = ["Walther Chen <walther.chen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.4"
futures-io = "0.3.4"
futures-util = "0.3.4"
http = "0.2.1"
httpdate = "0.3.2"
httparse = "1.3.4"
mime = "0.3.16"
pin-project-lite = "0.1.4"
thiserror = "1.0.16"

[dev-dependencies]
num_cpus = "1.13.0"
piper = "0.1.1"
smol = "0.1.4"
